version: "3"

services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=to_do
    ports:
      - 3306:3306

  app:
    build: .
    image: to_do/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=to_do
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - $PWD:/var/www/html:rw

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80 
